#include "shapes/circle.hpp"
#include "shapes/cuboid.hpp"
#include "shapes/line_2d.hpp"
#include "shapes/line_3d.hpp"
#include "shapes/point_2d.hpp"
#include "shapes/point_3d.hpp"
#include "shapes/rect.hpp"
#include "shapes/sphere.hpp"